<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Image;
use App\Entity\Event;
use App\Form\ImageType;
use App\Form\EventType;

class ImageController extends Controller
{
    /**
     * @Route("/image", name="image")
     */
    public function index(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $event = new Event();

        $event->addImage(new Image());

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            /** @var $file UploadedFile */

            $files = $event->getImages();
            $newDir = $event->eventNameConverterToDir($event->getEventName());

            foreach ($files as $file) {
                $uploadedFile = $file->getImage();
                foreach ($uploadedFile as $filed) {
                    $newImageName = $this->generateUniqueFileName() . '.' . $filed->guessExtension();
                    $this->resize_image($filed, 1000, 1000, false, $newImageName, $newDir);
                    $file->setImage($newImageName);
                    $em->merge($file);
                }
            }
            $em->persist($event);
            $em->flush();
        }
        return $this->render('image/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function resize_image($file, $w, $h, $crop = false, $image, $dir)
    {
        list($width, $height) = getimagesize($file);
        $r = $width / $height;
        if ($crop) {
            if ($width > $height) {
                $width = ceil($width - ($width * abs($r - $w / $h)));
            } else {
                $height = ceil($height - ($height * abs($r - $w / $h)));
            }
            $newwidth = $w;
            $newheight = $h;
        } else {
            if ($w / $h > $r) {
                $newwidth = $h * $r;
                $newheight = $h;
            } else {
                $newheight = $w / $r;
                $newwidth = $w;
            }
        }
        $imagePath = $this->getParameter('image_directory') . '/' . $dir . '/' . $image;

        $src = imagecreatefromjpeg($file);
        $dst = imagecreatetruecolor($newwidth, $newheight);
        imagecopyresampled($dst, $src, 0, 0, 0, 0, $newwidth, $newheight, $width, $height);
        if (!is_dir('uploads/images/' . $dir)) {
            mkdir('uploads/images/' . $dir, 0700);
        }
        imagejpeg($dst, $imagePath, 75);

        return $dst;
    }
}
